import React, { useState, useEffect } from 'react';
import { ProposalPDF } from './ProposalPDF.tsx';
import { AuthScreen } from './AuthComponents.tsx';
import {
  FormInput,
  FormSelect,
  FormCheckbox,
  FileUploader,
  SectionHeader,
  Button,
  DateRangePicker,
} from './InputComponents.tsx';
import {
  ProposalData,
  HotelDetails,
  FlightDetails,
  FlightClass,
  TransportationDetails,
  VehicleType,
  CustomItem,
  ActivityDetails,
  Inclusions,
  CategoryMarkups,
  MarkupType,
  FlightLeg,
  User,
  UserRole,
  ProposalHistory,
  MarkupConfig,
  RoomType,
  HotelImage,
  ImageTag,
  MeetingDetails,
  DiningDetails,
  FlightQuote,
  Company,
} from './types.ts';
import {
  BedIcon,
  PlaneIcon,
  BusIcon,
  ActivityIcon,
  CustomIcon,
  PalmLogo,
  SaveIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  HomeIcon,
  UserIcon,
  UsersIcon,
  LockIcon,
  UtensilsIcon,
  MeetingIcon,
  SITCLogo,
} from './Icons.tsx';
import {
  getGlobalSettings,
  saveGlobalSettings,
  getUsers,
  createSubUser,
  createCompanyAdmin,
  deleteUser,
  validatePassword,
  changePassword,
  updateUser,
  getCompanies,
  saveCompany,
  updateCompany,
  deleteCompany,
  adminResetUserPassword,
  validatePhone,
} from './authService.ts';
